services:
  db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app_net

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_net

  api:
    build: .
    restart: always
    depends_on:
      - db
      - rabbitmq
    environment:
      DB_HOST: db
      DB_PORT: '5432'
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: nest
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - app_net
    ports:
      - '3000:3000'
    command: npm run start:dev

volumes:
  db-data:
networks:
  app_net:
    driver: bridge
